feat: implement moving entry to trash bin
ProFile-org/ProFile-BE pull request #320
Opened 2023-07-02 03:50 UTC by StarryFolf

2023-07-02 05:14 UTC, ChienNQuang requested changes

2023-07-02 05:14 UTC, ChienNQuang commented on src/Api/Controllers/BinController.cs
> +    [RequiresRole(IdentityData.Roles.Staff, IdentityData.Roles.Employee)]
what is staff doing here?

2023-07-02 05:14 UTC, ChienNQuang commented on src/Application/Digital/Commands/MoveEntryToBin.cs
> +            if (binCheck.Contains(BinString))
you did not account for the fact that one entry contains many other entries

2023-07-09 11:35 UTC, kaitoz11 commented on src/Application/Digital/Commands/MoveEntryToBin.cs
> +            if (!entry.Owner.Username.Equals(request.CurrentUser.Username))
@StarryFolf 
Why using `username` instead of `id`?

2023-07-09 11:40 UTC, kaitoz11 approved these changes
LGTM

2023-07-10 17:01 UTC, ChienNQuang approved these changes
LGTM

2023-07-10 17:01 UTC, merged