Bao/add locker tests
ProFile-org/ProFile-BE pull request #74
Opened 2023-05-22 03:45 UTC by StarryFolf

feat: add tests for add locker

2023-05-22 06:34 UTC, ChienNQuang commented on src/Api/Controllers/LockersController.cs
> +    public async Task<ActionResult<Result<LockerDto>>> AddLocker([FromBody] CreateLockerCommand command)
Why you leave 2 changes in 2 different PR?

2023-05-22 06:35 UTC, ChienNQuang commented on src/Api/Controllers/LockersController.cs
> +    public async Task<ActionResult<Result<LockerDto>>> AddLocker([FromBody] CreateLockerCommand command)
and this change is completely out of no where in context of branch

2023-05-22 06:36 UTC, ChienNQuang commented on tests/Application.Tests.Integration/Lockers/Commands/CreateLockerTests.cs
> +    public async Task ShouldReturnLocker_WhenLockerDetailsAreValid()
WhenCreateDetails to be consistent with other tests

2023-05-22 06:36 UTC, ChienNQuang commented on tests/Application.Tests.Integration/Lockers/Commands/CreateLockerTests.cs
> +        room.NumberOfLockers += 1;
this is unnecessary

2023-05-22 06:40 UTC, ChienNQuang commented on tests/Application.Tests.Integration/Lockers/Commands/CreateLockerTests.cs
> +
Lack one assert of locker's number of lockers in room must increase by 1

2023-05-22 06:41 UTC, ChienNQuang commented on tests/Application.Tests.Integration/Lockers/Commands/CreateLockerTests.cs
> +        room.NumberOfLockers += 1;
this is not needed

2023-05-22 06:41 UTC, ChienNQuang commented on tests/Application.Tests.Integration/Lockers/Commands/CreateLockerTests.cs
> +        room.NumberOfLockers += 1;
this is not needed

2023-05-22 06:44 UTC, ChienNQuang commented on tests/Application.Tests.Integration/Lockers/Commands/CreateLockerTests.cs
> +    public async Task ShouldReturnLocker_WhenLockersHasSameNameButInDifferentRooms()
This test is unnecessary, the above one is sufficient already

2023-05-22 06:45 UTC, ChienNQuang commented on tests/Application.Tests.Integration/Lockers/Commands/CreateLockerTests.cs
> +        room.NumberOfLockers += 1;
this too is not needed

2023-05-22 06:45 UTC, ChienNQuang commented on tests/Application.Tests.Integration/Lockers/Commands/CreateLockerTests.cs
> +        room.NumberOfLockers += 1;
this too is not needed

2023-05-22 06:45 UTC, ChienNQuang requested changes
Very good but need some adjustment

2023-05-22 06:45 UTC, ChienNQuang requested changes
Very good but need some adjustment

2023-05-22 13:46 UTC, ChienNQuang commented on tests/Application.Tests.Integration/Lockers/Commands/AddLockerTests.cs
> +        var createLockerCommand2 = new AddLockerCommand()
This is unnecessary, using the same command

2023-05-22 13:47 UTC, ChienNQuang commented on tests/Application.Tests.Integration/Lockers/Commands/AddLockerTests.cs
> +        var locker = await SendAsync(createLockerCommand);
This should not be in Act

2023-05-22 13:47 UTC, ChienNQuang commented on tests/Application.Tests.Integration/Lockers/Commands/AddLockerTests.cs
> +    public async Task ShouldReturnLocker_WhenLockersHasSameNameButInDifferentRooms()
This test still is not necessary

2023-05-22 13:48 UTC, ChienNQuang commented on tests/Application.Tests.Integration/Lockers/Commands/AddLockerTests.cs
> +        var locker = await SendAsync(createLockerCommand);
This too should not be in Act

2023-05-22 13:49 UTC, ChienNQuang commented on tests/Application.Tests.Integration/Lockers/Commands/DisableLockerTests.cs
> +        var createLockerCommand = new AddLockerCommand()
createCommand = addCommand?

2023-05-22 13:49 UTC, ChienNQuang commented on tests/Application.Tests.Integration/Lockers/Commands/DisableLockerTests.cs
> +    public async Task ShouldRemoveLocker_WhenLockerExists()
This should be named ShouldDisableLocker_WhenLockerExistsAndIsAvailable

2023-05-22 13:51 UTC, ChienNQuang requested changes
Should add one more test in DisableLockerTests: Should do what when the locker is already disabled?

2023-05-23 15:44 UTC, kaitoz11 commented on src/Application/Lockers/Commands/DisableLocker/DisableLockerCommand.cs
> +        locker.Room.NumberOfLockers -= 1;
What should we do? @ChienNQuang @Vzart 
Keep or not?

2023-05-25 15:01 UTC, Vzart approved these changes
LGTM!

2023-05-25 15:01 UTC, ChienNQuang approved these changes

2023-05-25 15:01 UTC, merged